# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Install Nuget
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.2.0'

# Restore nuget packages
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(Agent.BuildDirectory)/TestDiscordBot.sln'
    feedsToUse: 'config'
    nugetConfigPath: '$(Agent.BuildDirectory)/NuGet.config'

# Build solution with VS 2019
- task: VSBuild@1
  inputs:
    solution: '$(Agent.BuildDirectory)/TestDiscordBot.sln'
    vsVersion: '16.0'
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'

# Publish .NET Core App
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(Agent.BuildDirectory)artifacts/'

# Publish artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Agent.BuildDirectory)/artifacts/'
    ArtifactName: 'Published Bot'
    publishLocation: 'Container'